In [2]:
import yfinance as yf

In [9]:
ticker = 'TSLA'
yf.Ticker(ticker).history(period='id', interval='15m').reset_index()
# show data every 15 minutes interval

,Datetime,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2023-11-10 09:30:00-05:00,208.949905,212.990005,208.279999,212.729996,14548362,0.0,0.0
1,2023-11-10 09:45:00-05:00,212.759995,213.679993,211.815308,212.269897,7789274,0.0,0.0
2,2023-11-10 10:00:00-05:00,212.229996,212.309998,209.281097,209.979996,8572130,0.0,0.0
3,2023-11-10 10:15:00-05:00,209.940002,210.149994,205.690002,207.099899,9115553,0.0,0.0
4,2023-11-10 10:30:00-05:00,207.061707,208.000000,206.639999,207.550003,5862084,0.0,0.0
5,2023-11-10 10:45:00-05:00,207.553604,209.550003,207.279999,209.168594,4982200,0.0,0.0
6,2023-11-10 11:00:00-05:00,209.179993,210.449997,208.160004,210.289993,5657047,0.0,0.0
7,2023-11-10 11:15:00-05:00,210.270004,211.240005,210.190002,210.429993,4389368,0.0,0.0
8,2023-11-10 11:30:00-05:00,210.429993,210.750000,209.279999,210.714996,4249773,0.0,0.0
9,2023-11-10 11:45:00-05:00,210.729904,212.330002,210.649994,212.244995,4863488,0.0,0.0
10,2023-11-10 12:00:00-05:00,212.250000,213.179993,211.750000,212.809998,5054599,0.0,0.0
11,2023-11-10 12:15:00-05:00,212.820297,212.960007,211.910004,212.649994,3840024,0.0,0.0
12,2023-11-10 12:30:00-05:00,212.630005,213.330002,212.009995,212.384995,3920438,0.0,0.0
13,2023-11-10 12:45:00-05:00,212.369995,213.000000,212.119995,212.729996,2861577,0.0,0.0
14,2023-11-10 13:00:00-05:00,212.729996,213.130005,212.270004,212.499893,2517667,0.0,0.0
15,2023-11-10 13:15:00-05:00,212.453796,213.460007,211.919998,213.229996,3498880,0.0,0.0
16,2023-11-10 13:30:00-05:00,213.220001,215.050003,213.220001,214.690002,4645035,0.0,0.0
17,2023-11-10 13:45:00-05:00,214.718994,215.199997,214.119995,214.660095,3303451,0.0,0.0
18,2023-11-10 14:00:00-05:00,214.679993,214.800003,214.000000,214.719894,3083602,0.0,0.0
19,2023-11-10 14:15:00-05:00,214.699997,215.380005,214.570007,214.809998,3323651,0.0,0.0
20,2023-11-10 14:30:00-05:00,214.809998,215.160004,214.179993,214.931107,2863117,0.0,0.0
21,2023-11-10 14:45:00-05:00,214.929993,215.350006,214.600906,214.945007,2648419,0.0,0.0
22,2023-11-10 15:00:00-05:00,214.949997,215.029999,213.619995,214.192200,3505216,0.0,0.0
23,2023-11-10 15:15:00-05:00,214.190002,215.080002,213.970001,214.869705,3269764,0.0,0.0
24,2023-11-10 15:30:00-05:00,214.860001,215.028900,214.050003,214.270096,3685267,0.0,0.0
25,2023-11-10 15:45:00-05:00,214.289993,214.921005,213.979996,214.690002,5283609,0.0,0.0